data_text<-readLines(file.choose())
head(data_text)
head(data_text,1)
length(grep("iconHomicideShooting"),data_text)
length(grep("iconHomicideShooting",data_text))
length(grep("iconHomicideShooting | icon_Homicide_Shooting",data_text))
length(grep("iconHomicideShooting|icon_Homicide_Shooting",data_text))
length(grep("iconHomicideShooting|icon_Hhomicide_shooting",data_text))
length(grep("iconHomicideShooting|icon_homicide_shooting",data_text))
length(grep("January",data_text))
length(grepl("January",data_text))
length(grepl("iconHomicideShooting|icon_homicide_shooting",data_text))
length(grepl("[Ss]hooting",data_text))
length(grep("[Ss]hooting",data_text))
length(grep("^[Ss]hooting",data_text))
length(grep("^[s]hooting",data_text))
length(grep("^shooting",data_text))
length(grepl("^January",data_text))
length(grep("^January",data_text))
grep("^New",state.name)
length(grep("^January",state.name))
View(state.name)
length(grep("^January",state.name))
length(grep("^Utah",state.name))
length(grep("Utah",state.name))
length(grepl("Utah",state.name))
length(grepl("^Utah",state.name))
grepl("^Utah",state.name,Value)
grepl("^Utah",state.name,Value=T)
grepl("^Utah",state.name,value=T)
grepl("^Utah",state.name,value=TRUE)
grep("^Utah",state.name,value=TRUE)
grep("new",state.name,value=TRUE)
grep("New",state.name,value=TRUE)
grep("india",state.name,value=TRUE)
grep("India",state.name,value=TRUE)
regexpr("<dd>[f]ound * </dd>")
regexpr("<dd>[f]ound * </dd>",data_text)
regexpr("<dd>[f]ound (*) </dd>",data_text)
regexpr("<dd>[f]ound (.*) </dd>",data_text)
regexpr("<dd>[Ff]ound(.*)</dd>",data_text[1:10])
regexpr("<dd>[Ff]ound(.*)</dd>",data_text)
regexpr("<dd>[Ff]ound(.*)</dd>",data_text[1:10])
substr(data_text[1],177,177+ 33-1)
regexpr("<dd>[Ff]ound(.*?)</dd>",data_text[1:10])
substr(data_text[1],177,177+ 33-1)
r<-regexpr("<dd>[Ff]ound(.*?)</dd>",data_text[1:100])
regmatches(data_text[1:100],r)
substr(data_text[1],177,177+ 33-1)
x<-substr(data_text[1],177,177+ 33-1)
sub("<dd>[Ff]ound on|</dd>")
sub("<dd>[Ff]ound on|</dd>","",x)
gsub("<dd>[Ff]ound on|</dd>","",x)
m<-regmatches(data_text[1:100],r)
gsub("<dd>[Ff]ound on|</dd>","",m)
date<-gsub("<dd>[Ff]ound on|</dd>","",m)
dates<-as.Date(date)
dates<-as.Date(date,"%B %d $Y")
dates
m<-regmatches(data_text[1:100],r)
dates<-sapply(m, function(x) x[2])
dates<-as.Date(dates,"%B %d %Y")
dates
